"""initial_schema

Revision ID: 9a0245401415
Revises: 
Create Date: 2026-03-10 21:24:18.566917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a0245401415'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instrument_token', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=50), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('oi', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('time', 'instrument_token', 'timeframe')
    )
    op.create_table('daily_pnl',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('strategy_id', sa.String(length=50), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('charges', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('num_trades', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'strategy_id')
    )
    op.create_table('instruments',
    sa.Column('instrument_token', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('instrument_type', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('underlying', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('instrument_token')
    )
    op.create_index(op.f('ix_instruments_expiry'), 'instruments', ['expiry'], unique=False)
    op.create_index(op.f('ix_instruments_tradingsymbol'), 'instruments', ['tradingsymbol'], unique=False)
    op.create_index(op.f('ix_instruments_underlying'), 'instruments', ['underlying'], unique=False)
    op.create_table('option_chain_snapshots',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying', sa.String(length=20), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('ltp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iv', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('delta', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('gamma', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('theta', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('vega', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('oi', sa.BigInteger(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ask_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('time', 'underlying', 'expiry', 'strike', 'option_type')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_order_id', sa.String(length=50), nullable=False),
    sa.Column('strategy_id', sa.String(length=50), nullable=False),
    sa.Column('instrument_token', sa.Integer(), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=50), nullable=False),
    sa.Column('order_side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('product', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('trigger_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fill_quantity', sa.Integer(), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_taken', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_event_type'), 'risk_events', ['event_type'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_states',
    sa.Column('strategy_id', sa.String(length=50), nullable=False),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('strategy_id')
    )
    op.create_table('ticks',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instrument_token', sa.Integer(), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=50), nullable=False),
    sa.Column('ltp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('oi', sa.BigInteger(), nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ask_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bid_qty', sa.Integer(), nullable=False),
    sa.Column('ask_qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('time', 'instrument_token')
    )
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.String(length=50), nullable=False),
    sa.Column('instrument_token', sa.Integer(), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('charges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=False)
    op.create_index(op.f('ix_trades_strategy_id'), 'trades', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_strategy_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('ticks')
    op.drop_table('strategy_states')
    op.drop_table('strategy_configs')
    op.drop_index(op.f('ix_risk_events_event_type'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('option_chain_snapshots')
    op.drop_index(op.f('ix_instruments_underlying'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_tradingsymbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_expiry'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_table('daily_pnl')
    op.drop_table('candles')
    # ### end Alembic commands ###
