"""add_advisory_and_confluence_tables

Revision ID: 6334855c1ad2
Revises: c2e068eaa83c
Create Date: 2026-04-13 17:59:30.634830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6334855c1ad2'
down_revision: Union[str, None] = 'c2e068eaa83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full_advisory', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('day_bias', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisories_date'), 'advisories', ['date'], unique=False)
    op.create_table('confluence_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agree_count', sa.Integer(), nullable=False),
    sa.Column('disagree_count', sa.Integer(), nullable=False),
    sa.Column('ai_right_count', sa.Integer(), nullable=False),
    sa.Column('rule_right_count', sa.Integer(), nullable=False),
    sa.Column('pnl_with_ai', sa.Float(), nullable=False),
    sa.Column('pnl_rules_only', sa.Float(), nullable=False),
    sa.Column('ai_alpha', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confluence_audits_date'), 'confluence_audits', ['date'], unique=True)
    op.create_table('decision_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strategy_id', sa.String(length=50), nullable=False),
    sa.Column('leg', sa.String(length=10), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('spot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vix', sa.Float(), nullable=False),
    sa.Column('pcr_oi', sa.Float(), nullable=False),
    sa.Column('max_pain', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_pain_dist_pct', sa.Float(), nullable=False),
    sa.Column('iv_skew_ratio', sa.Float(), nullable=False),
    sa.Column('move_from_open_pct', sa.Float(), nullable=False),
    sa.Column('morning_range_pct', sa.Float(), nullable=False),
    sa.Column('dte', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_expiry', sa.Integer(), nullable=False),
    sa.Column('rule_score', sa.Integer(), nullable=False),
    sa.Column('ai_adj', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('entry_premium', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('exit_reason', sa.String(length=100), nullable=False),
    sa.Column('outcome_pnl', sa.Float(), nullable=True),
    sa.Column('held_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_snapshots_strategy_id'), 'decision_snapshots', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_decision_snapshots_timestamp'), 'decision_snapshots', ['timestamp'], unique=False)
    op.drop_index(op.f('candles_time_idx'), table_name='candles')
    op.drop_index(op.f('option_chain_snapshots_time_idx'), table_name='option_chain_snapshots')
    op.drop_index(op.f('ticks_time_idx'), table_name='ticks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ticks_time_idx'), 'ticks', [sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('option_chain_snapshots_time_idx'), 'option_chain_snapshots', [sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('candles_time_idx'), 'candles', [sa.literal_column('time DESC')], unique=False)
    op.drop_index(op.f('ix_decision_snapshots_timestamp'), table_name='decision_snapshots')
    op.drop_index(op.f('ix_decision_snapshots_strategy_id'), table_name='decision_snapshots')
    op.drop_table('decision_snapshots')
    op.drop_index(op.f('ix_confluence_audits_date'), table_name='confluence_audits')
    op.drop_table('confluence_audits')
    op.drop_index(op.f('ix_advisories_date'), table_name='advisories')
    op.drop_table('advisories')
    # ### end Alembic commands ###
