"""A/B replay: portfolio strategy with advisor_confluence_enabled OFF vs ON.

Phase 4 of the Apr 18 audit follow-up. Sibling to ab_portfolio_filters.py.

The ADVISOR_CONFLUENCE_ENABLED flag exists in production (defaults to
False per the Apr 18 .env) but the live audit found 0/978 prior decisions
ever received an AI adjustment because live confidences ran 0.4-0.6 and
the gate was 0.7. So even in shadow mode the flag was effectively inert.

This harness runs a chain-replay A/B with synthetic per-day DayBias files
generated by `scripts/backfill_day_bias.py`. The synthetic confidences are
calibrated ABOVE 0.7 so adjustments actually fire — that's the whole point
of the test. The result measures *plumbing impact* (does the score
adjustment change which entries fire), NOT AI alpha (the bias is a
mechanical rule, not Claude's prediction).

Promotion implications: per `docs/FILTER_PROMOTION_RULES.md` the
advisor_confluence_enabled flag will not be flipped to default-ON based on
this test alone. The honest read of any delta here is "the wiring works,
adjustments propagate to entry decisions in the expected direction." A
real promotion decision needs (a) live AI bias above threshold for ≥30 days
and (b) the bootstrap-CI / tail-risk gates from the doc.

Pre-conditions:
  • Per-day backfill files exist in data/day_bias_backfill/
    (run scripts/backfill_day_bias.py first)
  • Chain snapshots in data/chain_snapshots/
  • PAPER_TRADING=false set before any strategy module loads (see
    ab_portfolio_filters.py for why — load_env() clobbers os.environ)
"""

from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

# Mirror ab_portfolio_filters.py's pre-import setup. The .env patch in
# main() handles the load_env() clobber problem.
os.environ["PAPER_TRADING"] = "false"

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

ENV_FILE = ROOT / ".env"
BACKFILL_DIR = ROOT / "data" / "day_bias_backfill"

from src.backtest.replay_engine import ReplayBacktestEngine  # noqa: E402

CAPITAL = 1_000_000
SNAPSHOT_DIR = "data/chain_snapshots"
SPOT_CSV = "data/nifty_spot_minute_chain.csv"
VIX_CSV = "data/india_vix_minute_chain.csv"


def fmt_inr(x: float) -> str:
    return f"₹{x:>+12,.2f}"


def get(metrics: dict, *keys, default=0):
    for k in keys:
        if k in metrics:
            return metrics[k]
    return default


async def run_one(confluence_on: bool, log_path: Path) -> dict:
    """Run one portfolio replay with ADVISOR_CONFLUENCE_ENABLED flipped.

    NOTE: Settings() loads from .env via pydantic-settings, AND
    scripts/auto_auth.load_env() unconditionally writes every .env value
    to os.environ on import. So setting os.environ here is not enough —
    the .env file itself must be patched and restored. Done in main()
    via _patch_env_file() with `confluence_on=...` flag.
    """
    import logging
    root = logging.getLogger()
    handler = logging.FileHandler(log_path, mode="w")
    handler.setLevel(logging.INFO)
    handler.setFormatter(logging.Formatter("%(message)s"))
    root.addHandler(handler)
    prev_level = root.level
    root.setLevel(logging.INFO)
    try:
        # Belt-and-suspenders: also set os.environ so any path that reads
        # straight from there picks it up. The .env file is the source of
        # truth though.
        os.environ["ADVISOR_CONFLUENCE_ENABLED"] = "true" if confluence_on else "false"
        os.environ["BACKFILL_DAY_BIAS_DIR"] = str(BACKFILL_DIR)
        # Filters stay OFF for both arms so any P&L delta is attributable
        # only to confluence — not to the PCR/max-pain hard filters.
        engine = ReplayBacktestEngine()
        result = await engine.run(
            strategy_name="portfolio",
            snapshot_dir=SNAPSHOT_DIR,
            spot_csv=SPOT_CSV,
            vix_csv=VIX_CSV,
            initial_capital=CAPITAL,
            strategy_params={"portfolio_filters_enabled": False},
        )
    finally:
        root.removeHandler(handler)
        handler.close()
        root.setLevel(prev_level)
    return result


def _count_confluence_lines(log_path: Path) -> dict[str, int]:
    """Count [CONFLUENCE] log lines in the per-run log."""
    counts = {"premium_low_conf": 0, "premium_applied": 0,
              "trend_low_conf": 0, "trend_applied": 0,
              "ignored_not_significant": 0}
    if not log_path.exists():
        return counts
    for line in log_path.read_text().splitlines():
        if "[CONFLUENCE]" not in line:
            continue
        if "leg=PREMIUM" in line:
            if "IGNORED(low_confidence)" in line:
                counts["premium_low_conf"] += 1
            elif "IGNORED(not_significant)" in line:
                counts["ignored_not_significant"] += 1
            elif "final=" in line or "would_be=" in line:
                counts["premium_applied"] += 1
        elif "leg=TREND" in line:
            if "IGNORED(low_confidence)" in line:
                counts["trend_low_conf"] += 1
            elif "IGNORED(not_significant)" in line:
                counts["ignored_not_significant"] += 1
            elif "final=" in line or "would_be=" in line:
                counts["trend_applied"] += 1
    return counts


def summarize(label: str, result: dict) -> dict:
    m = result.get("metrics", {})
    return {
        "label": label,
        "trades": get(m, "num_trades", "total_trades"),
        "win_rate": get(m, "win_rate"),
        "gross": get(m, "total_pnl") + get(m, "total_charges"),
        "charges": get(m, "total_charges"),
        "net": get(m, "total_pnl"),
        "sharpe": get(m, "sharpe_ratio"),
        "max_dd": get(m, "max_drawdown_pct"),
    }


def print_row(s: dict) -> None:
    print(
        f"{s['label']:<8} {s['trades']:>6}  "
        f"{s['win_rate']:>4.1f}%  {fmt_inr(s['gross'])} {fmt_inr(-s['charges'])} "
        f"{fmt_inr(s['net'])}  {(s['net']/CAPITAL)*100:>+6.3f}%  "
        f"{s['sharpe']:>+5.2f}  {s['max_dd']:>5.2f}%"
    )


def _patch_env_file(confluence_on: bool) -> str:
    """Force PAPER_TRADING=false AND ADVISOR_CONFLUENCE_ENABLED=<flag> in
    .env, return original for restore.

    Both keys must be patched here because scripts/auto_auth.load_env()
    clobbers os.environ on import — see ab_portfolio_filters.py header.
    """
    original = ENV_FILE.read_text()
    new_lines = []
    saw_paper = False
    saw_conf = False
    conf_value = "true" if confluence_on else "false"
    for line in original.splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("PAPER_TRADING="):
            new_lines.append("PAPER_TRADING=false\n")
            saw_paper = True
        elif stripped.startswith("ADVISOR_CONFLUENCE_ENABLED="):
            new_lines.append(f"ADVISOR_CONFLUENCE_ENABLED={conf_value}\n")
            saw_conf = True
        else:
            new_lines.append(line)
    if not saw_paper:
        new_lines.append("PAPER_TRADING=false\n")
    if not saw_conf:
        new_lines.append(f"ADVISOR_CONFLUENCE_ENABLED={conf_value}\n")
    ENV_FILE.write_text("".join(new_lines))
    return original


def _restore_env_file(original: str) -> None:
    ENV_FILE.write_text(original)


async def main() -> int:
    # Sanity check: backfill files must exist or this is a no-op.
    bf_files = sorted(BACKFILL_DIR.glob("day_bias_*.json")) if BACKFILL_DIR.exists() else []
    if not bf_files:
        print(f"ERROR: no backfill files in {BACKFILL_DIR}", file=sys.stderr)
        print(f"Run: uv run python scripts/backfill_day_bias.py", file=sys.stderr)
        return 1

    print(f"\nA/B replay — advisor confluence (synthetic DayBias)")
    print(f"Backfill files:  {len(bf_files)} days "
          f"({bf_files[0].stem.split('_', 2)[-1]} → {bf_files[-1].stem.split('_', 2)[-1]})")
    print(f"PAPER_TRADING = {os.environ['PAPER_TRADING']}")
    print("-" * 110)
    print(
        f"{'arm':<8} {'trades':>6}  {'win%':>4}  {'gross':>14} {'charges':>14} "
        f"{'net P&L':>14}  {'%cap':>6}  {'sharpe':>6}  {'maxDD':>6}"
    )
    print("-" * 110)

    log_off = Path("/tmp/ab_conf_off.log")
    log_on = Path("/tmp/ab_conf_on.log")
    # Snapshot the .env once; each run patches it from the same pristine
    # baseline so no run inherits the previous arm's flag setting.
    pristine_env = ENV_FILE.read_text()
    try:
        print("  running OFF run (confluence disabled) ...", flush=True)
        ENV_FILE.write_text(pristine_env)
        _patch_env_file(confluence_on=False)
        r_off = await run_one(confluence_on=False, log_path=log_off)
        s_off = summarize("OFF", r_off)
        print_row(s_off)

        print("  running ON  run (confluence enabled) ...", flush=True)
        ENV_FILE.write_text(pristine_env)
        _patch_env_file(confluence_on=True)
        r_on = await run_one(confluence_on=True, log_path=log_on)
        s_on = summarize("ON", r_on)
        print_row(s_on)
    finally:
        _restore_env_file(pristine_env)
        os.environ.pop("BACKFILL_DAY_BIAS_DIR", None)
        os.environ["ADVISOR_CONFLUENCE_ENABLED"] = "false"
        print(f"  (restored .env, cleared BACKFILL_DAY_BIAS_DIR)", flush=True)

    blocks_off = _count_confluence_lines(log_off)
    blocks_on = _count_confluence_lines(log_on)
    print(f"\n[CONFLUENCE] log lines:")
    print(f"  OFF (shadow): premium applied={blocks_off['premium_applied']} "
          f"trend applied={blocks_off['trend_applied']} "
          f"low_conf_ignored={blocks_off['premium_low_conf'] + blocks_off['trend_low_conf']}")
    print(f"  ON  (active): premium applied={blocks_on['premium_applied']} "
          f"trend applied={blocks_on['trend_applied']} "
          f"low_conf_ignored={blocks_on['premium_low_conf'] + blocks_on['trend_low_conf']}")

    print("-" * 110)
    delta_trades = s_on["trades"] - s_off["trades"]
    delta_net = s_on["net"] - s_off["net"]
    print(f"\nDelta (ON - OFF): trades {delta_trades:+d}, net P&L {fmt_inr(delta_net)}")
    print("\nReminder: per docs/FILTER_PROMOTION_RULES.md the synthetic-bias")
    print("delta is plumbing-impact only. Do NOT promote on this number alone.")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
