"""Weekly strategy scorecard — feeds the promotion criteria gate.

Scans the last 7 trading days of structured logs (logs/structured/*.jsonl)
and produces a markdown report with one section per strategy. Designed to
be run every Monday morning before market open as part of the promotion-
review process documented in docs/PROMOTION_CRITERIA.md.

Usage:
    uv run python scripts/weekly_review.py
    uv run python scripts/weekly_review.py --weeks 4 --out reports/weekly.md
    uv run python scripts/weekly_review.py --since 2026-04-10

The script is read-only — it never touches the DB or sends orders. Output
goes to stdout by default; pass --out to write a file.
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Iterable

LOG_DIR = Path("logs/structured")


@dataclass
class StrategyWeek:
    """Aggregated metrics for one strategy over the review window."""

    strategy_id: str
    entries: int = 0
    fills: int = 0
    submits: int = 0
    slippage_bps: list[float] = field(default_factory=list)
    fill_pnl_realized: float = 0.0  # Sum of P&L attribution if logged
    circuit_breaker_trips: int = 0
    reconcile_discrepancies: int = 0
    emergency_closes: int = 0
    error_count: int = 0
    days_active: set[date] = field(default_factory=set)

    def add_slippage(self, bps: float) -> None:
        # Filter the obvious zeros where price wasn't known — they bias the median
        if bps != 0:
            self.slippage_bps.append(abs(bps))

    @property
    def median_slippage_bps(self) -> float:
        return statistics.median(self.slippage_bps) if self.slippage_bps else 0.0

    @property
    def expected_fills(self) -> int:
        # Crude: assume 4 legs/entry for IC, 2 for strangle/straddle. We don't
        # know the strategy class from logs alone, so report both for context.
        return self.entries * 2  # 2-leg lower bound; reviewer eyeballs vs entries


def _iter_log_lines(log_dir: Path, since: date, until: date) -> Iterable[dict]:
    """Yield parsed JSON records from log files in [since, until]."""
    if not log_dir.exists():
        return
    for f in sorted(log_dir.glob("*.jsonl")):
        try:
            d = datetime.strptime(f.stem, "%Y-%m-%d").date()
        except ValueError:
            continue
        if not (since <= d <= until):
            continue
        with f.open() as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    yield json.loads(line)
                except json.JSONDecodeError:
                    continue


def aggregate(records: Iterable[dict]) -> dict[str, StrategyWeek]:
    """Build per-strategy aggregates from log records."""
    out: dict[str, StrategyWeek] = defaultdict(lambda: StrategyWeek(strategy_id=""))

    for rec in records:
        tag = rec.get("tag", "")
        sid = rec.get("strategy_id", "_unknown")
        sw = out[sid]
        if not sw.strategy_id:
            sw.strategy_id = sid

        ts = rec.get("timestamp", "")
        try:
            sw.days_active.add(datetime.fromisoformat(ts[:19]).date())
        except (ValueError, TypeError):
            pass

        if tag == "ENTRY":
            sw.entries += 1
        elif tag == "SUBMIT":
            sw.submits += 1
        elif tag == "FILL":
            sw.fills += 1
            slip_bps = rec.get("slippage_pct", 0)
            if isinstance(slip_bps, (int, float)):
                sw.add_slippage(float(slip_bps) * 100)  # pct → bps
        elif tag == "RECONCILE":
            sw.reconcile_discrepancies += int(rec.get("discrepancy_count", 0))
        elif tag == "CIRCUIT_BREAKER":
            sw.circuit_breaker_trips += 1
        elif tag == "EMERGENCY_CLOSE":
            sw.emergency_closes += 1
        elif tag == "ERROR":
            sw.error_count += 1

    # Drop the placeholder bucket if it's empty of meaningful events
    out.pop("_unknown", None)
    return dict(out)


def render_markdown(stats: dict[str, StrategyWeek], since: date, until: date) -> str:
    """Format the aggregate stats as a markdown report."""
    lines: list[str] = []
    lines.append(f"# Weekly Strategy Scorecard — {since.isoformat()} to {until.isoformat()}")
    lines.append("")
    lines.append(
        f"_Generated by `scripts/weekly_review.py`. See `docs/PROMOTION_CRITERIA.md` "
        f"for thresholds._"
    )
    lines.append("")

    if not stats:
        lines.append("**No strategy activity in this window.**")
        return "\n".join(lines)

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Strategy | Days | Entries | Fills | Med slip (bps) | CB trips | Recon disc. | Emerg close |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|")
    for sid, sw in sorted(stats.items()):
        lines.append(
            f"| `{sid}` | {len(sw.days_active)} | {sw.entries} | {sw.fills} "
            f"| {sw.median_slippage_bps:.1f} | {sw.circuit_breaker_trips} "
            f"| {sw.reconcile_discrepancies} | {sw.emergency_closes} |"
        )
    lines.append("")

    # Per-strategy detail with promotion-criteria flags
    for sid, sw in sorted(stats.items()):
        lines.append(f"## `{sid}`")
        lines.append("")
        flags: list[str] = []
        if sw.reconcile_discrepancies > 0:
            flags.append(f"**STOP-TRADING:** {sw.reconcile_discrepancies} reconcile discrepancies")
        if sw.circuit_breaker_trips > 0:
            flags.append(f"**REVIEW:** {sw.circuit_breaker_trips} circuit-breaker trip(s)")
        if sw.emergency_closes > 0:
            flags.append(f"**REVIEW:** {sw.emergency_closes} emergency-close event(s) — error path fired")
        if sw.error_count > 0:
            flags.append(f"**REVIEW:** {sw.error_count} unhandled error(s)")
        if sw.median_slippage_bps > 50:
            flags.append(
                f"**INVESTIGATE:** median slippage {sw.median_slippage_bps:.1f} bps "
                f"(promotion gate: <20 premium / <50 trend)"
            )
        if sw.entries > 0 and sw.fills < sw.entries:
            flags.append(
                f"**INVESTIGATE:** {sw.entries} entries → only {sw.fills} fills "
                f"(partial-fill or order-reject)"
            )
        if not flags:
            flags.append("No promotion-gate violations in this window.")
        for f in flags:
            lines.append(f"- {f}")
        lines.append("")
        lines.append(f"- Active days: {len(sw.days_active)} of {(until - since).days + 1}")
        lines.append(f"- Submits / Fills: {sw.submits} / {sw.fills}")
        if sw.slippage_bps:
            lines.append(
                f"- Slippage bps: median {sw.median_slippage_bps:.1f}, "
                f"p95 {statistics.quantiles(sw.slippage_bps, n=20)[-1]:.1f}, "
                f"max {max(sw.slippage_bps):.1f}, n={len(sw.slippage_bps)}"
            )
        lines.append("")

    # Promotion gate hint
    lines.append("---")
    lines.append("")
    lines.append("## Next steps")
    lines.append("")
    lines.append("1. For each strategy with a STOP-TRADING flag: **halt orders** and reconcile.")
    lines.append("2. For REVIEW flags: open the relevant log day and walk the event chain.")
    lines.append("3. For strategies tier-promoted last week: apply the 20-day capital-tier rules in `docs/PROMOTION_CRITERIA.md`.")
    lines.append("4. Commit this report under `reports/weekly/<date>.md` for the audit trail.")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--log-dir", type=Path, default=LOG_DIR,
        help="Directory of YYYY-MM-DD.jsonl files (default: logs/structured)",
    )
    parser.add_argument(
        "--weeks", type=int, default=1,
        help="Number of weeks to look back (default: 1)",
    )
    parser.add_argument(
        "--since", type=str, default="",
        help="Override start date (YYYY-MM-DD); takes precedence over --weeks",
    )
    parser.add_argument(
        "--until", type=str, default="",
        help="Override end date (YYYY-MM-DD); defaults to today",
    )
    parser.add_argument(
        "--out", type=Path, default=None,
        help="Write report to this path instead of stdout",
    )
    args = parser.parse_args()

    until = date.fromisoformat(args.until) if args.until else date.today()
    if args.since:
        since = date.fromisoformat(args.since)
    else:
        since = until - timedelta(days=7 * args.weeks - 1)

    records = list(_iter_log_lines(args.log_dir, since, until))
    if not records:
        print(
            f"No log records found in {args.log_dir} for [{since}, {until}].",
            file=sys.stderr,
        )

    stats = aggregate(records)
    report = render_markdown(stats, since, until)

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(report)
        print(f"Wrote report → {args.out}")
    else:
        print(report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
